{% set name = "mitmproxy_wireguard" %}
{% set version = "0.1.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mitmproxy_wireguard-{{ version }}.tar.gz
  sha256: b0f7b44ef9b0601307c122c5fe1ce57368c2fc9330097ec576984a0d640b4727

build:
  script:
    {% if build_platform != target_platform %}
    - export PYO3_CROSS_INCLUDE_DIR=$PREFIX/include
    - export PYO3_CROSS_LIB_DIR=$PREFIX/lib/python$PY_VER
    - export PYO3_CROSS_PYTHON_VERSION=$PY_VER
    {% endif %}
    - {{ PYTHON }} -m pip install . -vv
  number: 1
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - python
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=0.13,<0.14                   # [build_platform != target_platform]
  host:
    - maturin >=0.13,<0.14
    - python
    - pip
  run:
    - python

test:
  imports:
    - mitmproxy_wireguard
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/mitmproxy-wireguard/
  summary: WireGuard interface for mitmproxy
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AdrianFreundQC
    - freundTech
